In [36]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier


In [4]:
df = pd.read_csv('Task 3 and 4_Loan_Data.csv')

In [5]:
df.head()

customer_id  credit_lines_outstanding  loan_amt_outstanding  \
0      8153374                         0           5221.545193   
1      7442532                         5           1958.928726   
2      2256073                         0           3363.009259   
3      4885975                         0           4766.648001   
4      4700614                         1           1345.827718   

   total_debt_outstanding       income  years_employed  fico_score  default  
0             3915.471226  78039.38546               5         605        0  
1             8228.752520  26648.43525               2         572        1  
2             2027.830850  65866.71246               4         602        0  
3             2501.730397  74356.88347               5         612        0  
4             1768.826187  23448.32631               6         631        0

In [9]:
df.describe()

customer_id  credit_lines_outstanding  loan_amt_outstanding  \
count  1.000000e+04              10000.000000          10000.000000   
mean   4.974577e+06                  1.461200           4159.677034   
std    2.293890e+06                  1.743846           1421.399078   
min    1.000324e+06                  0.000000             46.783973   
25%    2.977661e+06                  0.000000           3154.235371   
50%    4.989502e+06                  1.000000           4052.377228   
75%    6.967210e+06                  2.000000           5052.898103   
max    8.999789e+06                  5.000000          10750.677810   

       total_debt_outstanding         income  years_employed    fico_score  \
count            10000.000000   10000.000000    10000.000000  10000.000000   
mean              8718.916797   70039.901401        4.552800    637.557700   
std               6627.164762   20072.214143        1.566862     60.657906   
min                 31.652732    1000.000000        0.000000    408.000000   
25%               4199.836020   56539.867903        3.000000    597.000000   
50%               6732.407217   70085.826330        5.000000    638.000000   
75%              11272.263740   83429.166133        6.000000    679.000000   
max              43688.784100  148412.180500       10.000000    850.000000   

            default  
count  10000.000000  
mean       0.185100  
std        0.388398  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [11]:
dfcp = df.iloc[:,1:]

In [12]:
dfcp.head()

credit_lines_outstanding  loan_amt_outstanding  total_debt_outstanding  \
0                         0           5221.545193             3915.471226   
1                         5           1958.928726             8228.752520   
2                         0           3363.009259             2027.830850   
3                         0           4766.648001             2501.730397   
4                         1           1345.827718             1768.826187   

        income  years_employed  fico_score  default  
0  78039.38546               5         605        0  
1  26648.43525               2         572        1  
2  65866.71246               4         602        0  
3  74356.88347               5         612        0  
4  23448.32631               6         631        0

In [13]:
dfcp.shape

(10000, 7)

In [14]:
dfcp['default'].value_counts()

0    8149
1    1851
Name: default, dtype: int64

In [15]:
dfcp.groupby('default').mean()

credit_lines_outstanding  loan_amt_outstanding  \
default                                                   
0                        0.744140           4092.629025   
1                        4.618044           4454.854897   

         total_debt_outstanding        income  years_employed  fico_score  
default                                                                    
0                   6322.164549  69883.889804        4.765247  646.938765  
1                  19270.582961  70726.740140        3.617504  596.257699

In [16]:
X = dfcp.drop(columns= 'default', axis = 1)
Y = dfcp['default']

In [18]:
X

credit_lines_outstanding  loan_amt_outstanding  total_debt_outstanding  \
0                            0           5221.545193             3915.471226   
1                            5           1958.928726             8228.752520   
2                            0           3363.009259             2027.830850   
3                            0           4766.648001             2501.730397   
4                            1           1345.827718             1768.826187   
...                        ...                   ...                     ...   
9995                         0           3033.647103             2553.733144   
9996                         1           4146.239304             5458.163525   
9997                         2           3088.223727             4813.090925   
9998                         0           3288.901666             1043.099660   
9999                         1           1917.652480             3050.248203   

           income  years_employed  fico_score  
0     78039.38546               5         605  
1     26648.43525               2         572  
2     65866.71246               4         602  
3     74356.88347               5         612  
4     23448.32631               6         631  
...           ...             ...         ...  
9995  42691.62787               5         697  
9996  79969.50521               8         615  
9997  38192.67591               5         596  
9998  50929.37206               2         647  
9999  30611.62821               6         757  

[10000 rows x 6 columns]

In [20]:
Y

0       0
1       1
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: default, Length: 10000, dtype: int64

In [21]:
scaler = StandardScaler()

In [143]:
scaler.fit(X)

StandardScaler()

In [144]:
std_data = scaler.transform(X)

In [145]:
std_data

array([[-0.83795996,  0.74709578, -0.72484779,  0.39855514,  0.28542543,
        -0.53676973],
       [ 2.02940918, -1.54837469, -0.07396659, -2.16187589, -1.62932476,
        -1.08083154],
       [-0.83795996, -0.56050945, -1.00969582, -0.20791915, -0.35282464,
        -0.58622989],
       ...,
       [ 0.3089877 , -0.75383958, -0.58939551, -1.58671175,  0.28542543,
        -0.68515022],
       [-0.83795996, -0.61264913, -1.15829336, -0.95213636, -1.62932476,
         0.15567257],
       [-0.26448613, -1.57741531, -0.85541136, -1.96441929,  0.92367549,
         1.96921192]])

In [27]:
X1 =  std_data


In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(X1, Y, test_size=0.2, stratify=Y)

In [29]:
X1.shape

(10000, 6)

In [30]:
X_train.shape

(8000, 6)

In [32]:
classifier = svm.SVC(kernel='linear')

In [33]:
classifier.fit(X_train, Y_train.values)

SVC(kernel='linear')

In [34]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train.values)

In [37]:
print(f'Accuracy score of the training data: {training_data_accuracy}')

Accuracy score of the training data: 0.998


In [38]:
classifier2 = DecisionTreeClassifier()
classifier2 = classifier2.fit(X_train, Y_train)

In [39]:
y_preds = classifier2.predict(X_train)

In [40]:
accuracy = accuracy_score(y_preds, Y_train.values)

In [41]:
print(f'Accuracy score of the training data: {training_data_accuracy}')

Accuracy score of the training data: 0.998


In [42]:
from sklearn.linear_model import LogisticRegression 


In [43]:
classifier3 = LogisticRegression()

In [45]:
classifier3 = classifier3.fit(X_train, Y_train)

In [46]:
y_preds3 = classifier3.predict(X_test)

In [47]:
accuracy3 = accuracy_score(y_preds3, Y_test)

In [48]:
print(f'The accuracy score of logistic regression is: {accuracy3}')

The accuracy score of logistic regression is: 0.997


In [49]:
X_test.shape

(2000, 6)

In [130]:
(customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
)= (5171615,5,5668.377526,20796.78546,66612.36864,3,571,1)


In [131]:
customer_id

5171615

In [110]:
credit_lines_outstanding

4

In [146]:
def predictor(credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score):
    tester = np.array([[credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score]])
    tester = tester.reshape(1,-1)
    print(tester)
    new_std = scaler.transform(tester)
    print(new_std)
    prediction = classifier.predict(new_std)
    return prediction

In [147]:
prediction = predictor(credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score
)
print(f'prediction for the given data is: {prediction}')

[[5.00000000e+00 5.66837753e+03 2.07967855e+04 6.66123686e+04
  3.00000000e+00 5.71000000e+02]]
[[ 2.02940918  1.06147243  1.82257014 -0.17076861 -0.9910747  -1.09731826]]
[[ 2.02940918  1.06147243  1.82257014 -0.17076861 -0.9910747  -1.09731826]]
prediction for the given data is: [1]


c:\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
